% Co-registration  matlabbatch commands.
% << to be incorporated into Multi-subject/session/run structure >>

 % In the lines below change the filename to where the Mean image file (generated by Realignment step), and Structural image file are for you.   Usually for the Mean image this will be your fMRI source 
%     images directory because Matlab saves the mean image there by default.  For the Structural image check your own project directory.
matlabbatch{1}.spm.spatial.coreg.estimate.ref = {'C:\Users\KW\Documents\DATA\MoAEpilot\fM00223\meanfM00223_016.img,1'}; 
matlabbatch{1}.spm.spatial.coreg.estimate.source = {'C:\Users\KW\Documents\DATA\MoAEpilot\sM00223\sM00223_002.img,1'};
matlabbatch{1}.spm.spatial.coreg.estimate.other = {''};
matlabbatch{1}.spm.spatial.coreg.estimate.eoptions.cost_fun = 'nmi';
matlabbatch{1}.spm.spatial.coreg.estimate.eoptions.sep = [4 2];
matlabbatch{1}.spm.spatial.coreg.estimate.eoptions.tol = [0.02 0.02 0.02 0.001 0.001 0.001 0.01 0.01 0.01 0.001 0.001 0.001];
matlabbatch{1}.spm.spatial.coreg.estimate.eoptions.fwhm = [7 7];
