%% PREPROCESSING 
% STEP 1.1: Co-registration
% Function name:    coregister_job
% Description:      coregisters realigned fMRI img files
% Arguments:        mean_functional_img (mean image file generated by realignment step 1)
%                   structural_img (structural image)
% Outputs:          ps image file with co-registration

function [c_img] = coregister_job(mean_functional_img, structural_img)
    
    clear matlabbatch % clear matlabbatch

    matlabbatch{1}.spm.spatial.coreg.estimate.ref = cellstr(mean_functional_img);   % select mean realigned image
    matlabbatch{1}.spm.spatial.coreg.estimate.source = cellstr(structural_img); % select structural image
    
    % set parameters
    matlabbatch{1}.spm.spatial.coreg.estimate.other = {''};
    matlabbatch{1}.spm.spatial.coreg.estimate.eoptions.cost_fun = 'nmi';
    matlabbatch{1}.spm.spatial.coreg.estimate.eoptions.sep = [4 2];
    matlabbatch{1}.spm.spatial.coreg.estimate.eoptions.tol = [0.02 0.02 0.02 0.001 0.001 0.001 0.01 0.01 0.01 0.001 0.001 0.001];
    matlabbatch{1}.spm.spatial.coreg.estimate.eoptions.fwhm = [7 7];

    c_img = matlabbatch;

    % perform co-registration
    spm_jobman('run', c_img);

    clear matlabbatch % clear matlabbatch

end
